version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${pass}
      POSTGRES_DB: ${name}
    container_name: oxxo_db
    volumes:
      - ./postgres:/var/lib/postgresql/data